### ISSUE TITLE
help me create a CONTRIBUTE.md file

### ISSUE THREAD

**Issue by stefanmiodrag** [stefanmiodrag/code-collection#2]
Hey,

Need help with creating a basic CONTRIBUTE.md file. The purpose of this repository is to store and create an achieve of code learnings. Anyone will be able to either create a new .md file or edit an existing one in case they'd like to add or change anything in the text.

Let me know if you have any questions and I'm happy to help assist anyone 😄

**Comment by dhairyagada** [comment]
Hey, 
Did you mean to say that you want to create just an archive with a list of relevant links for learning to code?

**Comment by stefanmiodrag** [comment]
@dhairyagada Nope. It'd be .md files in the form of articles / courses. They'd then be organized by category, language, etc.
